# Generated by Django 2.1.5 on 2019-06-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaremodel',
            name='name',
            field=models.CharField(help_text='이름을 입력하세요', max_length=20),
        ),
    ]
