# Generated by Django 2.1.5 on 2019-06-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0002_auto_20190627_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaremodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
