# Generated by Django 2.1.5 on 2019-06-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0003_auto_20190627_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwaremodel',
            name='username',
        ),
        migrations.DeleteModel(
            name='HardwareModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
