# Generated by Django 2.1.5 on 2019-06-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wifi', '0004_auto_20190627_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceList',
            fields=[
                ('list_seq', models.AutoField(primary_key=True, serialize=False)),
                ('sniff_time', models.DateTimeField()),
                ('mac_list', models.TextField()),
            ],
            options={
                'db_table': 'device_list',
                'managed': False,
            },
        ),
    ]
