# Generated by Django 2.1.5 on 2019-06-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0005_devicelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicelist',
            options={},
        ),
    ]
