# Generated by Django 2.1.5 on 2019-06-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0006_auto_20190627_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicelist',
            options={'managed': False},
        ),
    ]
