# Generated by Django 2.2.2 on 2019-06-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190627_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountUsingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_time', models.DateTimeField()),
            ],
        ),
    ]
